'use client';
import {PlanNotice,PlanLink} from './plan-notice';
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {ArrowLeft,ArrowRight,ArrowRightLeft,CreditCard,Filter,Plus,Search,Wallet} from 'lucide-react';
import {BottomNav} from '@/components/custom/bottom-nav';
import {BankCard,FilterPills,RoundButton,ScreenHeader} from './finance-ui';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Label} from '@/components/ui/label';
import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle} from '@/components/ui/dialog';
import {ResourceState,formatMoney,formatDate} from '@/components/data/resource-state';
import {apiRequest,useResource} from '@/hooks/useResource';
import {todayBR,toCents} from '@/lib/domain/validation';
import {dailySchemas,type DailyOperation} from '@/lib/domain/daily';
import type {DailySnapshot,DailyTransaction} from '@/lib/daily.types';
import {formFields,operationTitles,type FormValues} from './daily-forms';
const nativeSelect='w-full bg-glass-deep border rounded-xl p-3 text-sm';
const notes:Partial<Record<DailyOperation,string>>={
 'account.save':'O saldo inicial não conta como receita. Depois do cadastro, corrija o saldo com um ajuste identificado. Para arquivar, zere o saldo e resolva as pendências.',
 'transaction.save':'A competência organiza o mês. Somente lançamentos pagos ou recebidos alteram o saldo da conta, pela data de realização.',
 'transfer.save':'Este registro movimenta suas duas contas no controle do app. Não envia dinheiro pelo banco e não é receita nem despesa.',
 'card.save':'Se o dia não existir no mês, usamos o último dia. Depois de gerar faturas, as datas de fechamento e vencimento ficam preservadas.',
 'purchase.save':'Informe o valor total da compra. Compras no dia do fechamento entram no próximo ciclo. Editar altera todas as parcelas; faturas com pagamentos precisam ter esses registros corrigidos antes.',
 'payment.save':'Registra um pagamento que você fez no banco. O app não envia dinheiro. Pagamentos parciais mantêm o restante da fatura pendente.',
 'adjustment.save':'Use um valor positivo para acrescentar e negativo para reduzir o saldo. O ajuste aparece no histórico, sem virar receita ou despesa.',
};
export default function DailyWorkspace({mode}:{mode:'accounts'|'transactions'|'cards'}){
 const [month,setMonth]=useState(()=>todayBR().slice(0,7)),[page,setPage]=useState(0),[type,setType]=useState('all'),[status,setStatus]=useState('all'),[category,setCategory]=useState(''),[query,setQuery]=useState(''),[search,setSearch]=useState(''),[filters,setFilters]=useState(false),[tab,setTab]=useState<'transactions'|'transfers'|'payments'|'adjustments'>('transactions');
 useEffect(()=>{const timer=setTimeout(()=>{setSearch(query);setPage(0);},250);return()=>clearTimeout(timer);},[query]);
 const resource=useResource<DailySnapshot>(`/api/daily?month=${month}&page=${page}&type=${type}&status=${status}&category=${category}&search=${encodeURIComponent(search)}`);
 const [operation,setOperation]=useState<DailyOperation|null>(null),[values,setValues]=useState<FormValues>({}),[saving,setSaving]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[chooser,setChooser]=useState(false),[selectedCard,setSelectedCard]=useState(''),[detailsLoading,setDetailsLoading]=useState(false);
 const retry=useRef<{payload:string;key:string}|null>(null),submitting=useRef(false);
 const data=resource.data;
 useEffect(()=>{const m=new URLSearchParams(window.location.search).get('month');if(m&&/^\d{4}-(0[1-9]|1[0-2])$/.test(m)&&m>='1900-01'&&m<='2200-12')setMonth(m);},[]);
 function open(op:DailyOperation,initial:FormValues={}){
  const today=todayBR();setError('');setMessage('');setChooser(false);retry.current=null;
  const defaults:Partial<Record<DailyOperation,FormValues>>={
   'account.save':{nome:'',tipo:'corrente',saldo_inicial:'0',data_saldo_inicial:today,incluir_no_disponivel:true},
   'transaction.save':{descricao:'',tipo:'despesa',valor:'',conta_id:data?.accounts.find(a=>!a.arquivada)?.id||'',categoria_id:'',data_competencia:today,data_vencimento:today,status:'realizado',data_realizacao:today,observacoes:''},
   'transfer.save':{conta_origem_id:'',conta_destino_id:'',valor:'',data:today},
   'card.save':{nome:'',bandeira:'Mastercard',limite:'',dia_fechamento:10,dia_vencimento:20},
   'purchase.save':{descricao:'',cartao_id:selectedCard||data?.cards.find(c=>!c.arquivado)?.id||'',categoria_id:'',valor:'',data_compra:today,parcelas:1},
   'payment.save':{conta_id:data?.accounts.find(a=>!a.arquivada)?.id||'',valor:'',data:today},
   'adjustment.save':{conta_id:'',valor:'',data:today,motivo:''},
  };const next={...defaults[op],...initial};if(op==='account.save'&&next.id){delete next.saldo_inicial;delete next.data_saldo_inicial;}setValues(next);setOperation(op);
 }
 function close(){if(!submitting.current){setOperation(null);setError('');}}
 async function save(event:React.FormEvent){event.preventDefault();if(!operation||submitting.current)return;setError('');
  const payload={...values};if(operation==='transaction.save'&&payload.status==='previsto')payload.data_realizacao=null;
  const checked=dailySchemas[operation].safeParse(payload);if(!checked.success){setError(checked.error.issues[0].message);return;}
  const serialized=JSON.stringify({operation,data:checked.data});if(retry.current?.payload!==serialized)retry.current={payload:serialized,key:crypto.randomUUID()};
  submitting.current=true;setSaving(true);
  try{await apiRequest('/api/daily',{method:'POST',body:JSON.stringify({operation,data:checked.data,requestId:retry.current.key})});setOperation(null);setMessage(operation.endsWith('.delete')?'Registro excluído. Os totais foram recalculados.':'Dados salvos.');retry.current=null;resource.reload();}
  catch(e){setError(e instanceof Error?e.message:'Não foi possível salvar.');}finally{submitting.current=false;setSaving(false);}
 }
 async function editTransaction(t:DailyTransaction){
  if(t.recorrencia_id){window.location.assign('/recorrencias');return;}
  if(t.compra_id){setDetailsLoading(true);setError('');try{const result=await apiRequest<{purchase:DailyTransaction[]}>(`/api/daily?purchase=${t.compra_id}`);const rows=result.purchase;const first=rows[0];if(!first)throw new Error('Compra não encontrada.');open('purchase.save',{id:t.compra_id,cartao_id:first.cartao_id!,descricao:first.descricao,valor:String(rows.reduce((sum,r)=>sum+toCents(String(r.valor)),0)/100),categoria_id:first.categoria_id,data_compra:first.data_compra!,parcelas:rows.length});}catch(e){setError(e instanceof Error?e.message:'Não foi possível abrir a compra.');}finally{setDetailsLoading(false);}return;}
  if(!t.conta_id){setError('Esta compra pertence à estrutura anterior e precisa de revisão antes da edição.');return;}
  open('transaction.save',{id:t.id,descricao:t.descricao,tipo:t.tipo,valor:String(t.valor),categoria_id:t.categoria_id,conta_id:t.conta_id,data_competencia:t.data_competencia,data_vencimento:t.data_vencimento,data_realizacao:t.data_realizacao,status:t.status,observacoes:t.observacoes||''});
 }
 function shiftMonth(direction:number){const d=new Date(month+'-15T12:00:00Z');d.setUTCMonth(d.getUTCMonth()+direction);setMonth(d.toISOString().slice(0,7));setPage(0);}
 const title=mode==='accounts'?'Minhas contas':mode==='cards'?'Meus Cartões':'Lançamentos';
 const card=data?.cards.find(c=>c.id===selectedCard)||data?.cards[0];
 const changeTab=(value:typeof tab)=>{setTab(value);setPage(0);};
 const accountName=(id:string)=>data?.accounts.find(a=>a.id===id)?.nome||'Conta';
 const maxCount=data?.counts[mode==='accounts'?(tab==='transfers'?'transfers':'adjustments'):mode==='cards'?'payments':tab]||0;
 const formDelete:Partial<Record<DailyOperation,DailyOperation>>={'transaction.save':'transaction.delete','transfer.save':'transfer.delete','purchase.save':'purchase.delete'};
 return <main className="app-shell finance-shell">
  <ScreenHeader title={title}><RoundButton label={mode==='accounts'?'Adicionar conta':mode==='cards'?'Adicionar cartão':'Novo lançamento'} onClick={()=>mode==='transactions'?setChooser(true):open(mode==='accounts'?'account.save':'card.save')}><Plus/></RoundButton></ScreenHeader>
  <PlanNotice/><div className="daily-month"><Button variant="ghost" size="icon" aria-label="Mês anterior" onClick={()=>shiftMonth(-1)} disabled={month<='1900-01'}><ArrowLeft/></Button><label><span className="sr-only">Mês de consulta</span><Input type="month" min="1900-01" max="2200-12" value={month} onChange={e=>{if(e.target.value){setMonth(e.target.value);setPage(0);}}}/></label><Button variant="ghost" size="icon" aria-label="Próximo mês" onClick={()=>shiftMonth(1)} disabled={month>='2200-12'}><ArrowRight/></Button></div>
  {message&&<p role="status" className="daily-message">{message}</p>}{!operation&&error&&<p role="alert" className="text-red-300 text-sm my-3">{error}</p>}
  <ResourceState {...resource} retry={resource.reload}/>
  {data&&<>
   {mode==='transactions'&&<>
    <div className="filter-toolbar"><FilterPills values={[{value:'all',label:'Todos'},{value:'receita',label:'Receitas'},{value:'despesa',label:'Despesas'}]} selected={type} onChange={v=>{setType(v);setPage(0);}}/><RoundButton label="Busca e filtros" onClick={()=>setFilters(v=>!v)}><Filter/></RoundButton></div>
    {filters&&<div className="glass-panel p-4 space-y-3 mb-4"><Label htmlFor="daily-search"><Search className="size-4 inline mr-2"/>Buscar descrição</Label><Input id="daily-search" value={query} onChange={e=>setQuery(e.target.value)} maxLength={160}/><Label htmlFor="daily-status">Situação</Label><select id="daily-status" className={nativeSelect} value={status} onChange={e=>{setStatus(e.target.value);setPage(0);}}><option value="all">Todas</option><option value="previsto">Pendente / previsto</option><option value="realizado">Pago / recebido / fatura quitada</option></select><Label htmlFor="daily-category">Categoria</Label><select id="daily-category" className={nativeSelect} value={category} onChange={e=>{setCategory(e.target.value);setPage(0);}}><option value="">Todas</option>{data.categories.map(c=><option key={c.id} value={c.id}>{c.nome}</option>)}</select><Button variant="ghost" onClick={()=>{setType('all');setStatus('all');setCategory('');setQuery('');setSearch('');setPage(0);}}>Limpar filtros</Button></div>}
    <div className="daily-totals"><div><span>Receitas na seleção</span><strong className="money-positive">{formatMoney(data.totals.income)}</strong></div><div><span>Despesas na seleção</span><strong className="money-negative">{formatMoney(data.totals.expenses)}</strong></div></div><p className="daily-hint">Por competência, incluindo previsões e parcelas. Estes totais não são o saldo bancário.</p>
    <div className="daily-tabs"><button aria-pressed={tab==='transactions'} onClick={()=>changeTab('transactions')}>Lançamentos</button><button aria-pressed={tab==='transfers'} onClick={()=>changeTab('transfers')}>Transferências</button></div>
    {tab==='transactions'?(data.transactions.length?<div className="glass-panel transaction-list">{data.transactions.map(t=><button className="transaction-row" key={t.id} disabled={detailsLoading} onClick={()=>void editTransaction(t)}><span className={`icon-tile ${t.tipo==='receita'?'icon-tile--green':'icon-tile--gold'}`}>{t.cartao_id?<CreditCard/>:<Wallet/>}</span><span className="transaction-row__description"><strong>{t.descricao}{t.parcela?` · ${t.parcela}/${t.total_parcelas}`:''}</strong><small>{formatDate(t.data_competencia)} · {t.cartao_id?'Na fatura':t.status==='realizado'?'Realizado':'Previsto'} · {data.categories.find(c=>c.id===t.categoria_id)?.nome}</small></span><span className={t.tipo==='receita'?'money-positive':'money-negative'}>{t.tipo==='receita'?'+':'−'} {formatMoney(t.valor)}</span></button>)}</div>:<Empty title="Nenhum lançamento neste período" text="Registre uma receita, despesa ou compra para começar."/>):<Transfers rows={data.transfers} accountName={accountName} edit={v=>open('transfer.save',v)}/>}
   </>}
   {mode==='accounts'&&<>
    {!data.accounts.length&&<Empty title="Cadastre sua primeira conta" text="Informe o saldo de abertura para começar seu controle."/>}
    <div className="daily-account-grid">{data.accounts.map(a=><section key={a.id} className="glass-panel p-5 space-y-3"><div className="flex items-center justify-between gap-3"><h2 className="font-semibold break-words">{a.nome}</h2><Wallet className="size-5 text-primary shrink-0"/></div><strong className="text-2xl block">{formatMoney(a.saldo_atual)}</strong><p className="daily-hint">{a.arquivada?'Arquivada':a.incluir_no_disponivel?'Incluída no disponível':'Fora do disponível'} · Abertura {formatDate(a.data_saldo_inicial)}: {formatMoney(a.saldo_inicial)}</p><div className="flex gap-2 flex-wrap"><Button size="sm" variant="outline" onClick={()=>open('account.save',{id:a.id,nome:a.nome,tipo:a.tipo,incluir_no_disponivel:a.incluir_no_disponivel,arquivada:a.arquivada})}>Editar</Button>{!a.arquivada&&<Button size="sm" variant="ghost" onClick={()=>open('adjustment.save',{conta_id:a.id})}>Ajustar saldo</Button>}</div></section>)}</div>
    <Button className="my-5" variant="outline" onClick={()=>open('transfer.save')}><ArrowRightLeft/>Registrar transferência</Button>
    <div className="daily-tabs"><button aria-pressed={tab==='transfers'} onClick={()=>changeTab('transfers')}>Transferências</button><button aria-pressed={tab!=='transfers'} onClick={()=>changeTab('adjustments')}>Ajustes de saldo</button></div>
    {tab==='transfers'?<Transfers rows={data.transfers} accountName={accountName} edit={v=>open('transfer.save',v)}/>:<div className="content-stack">{data.adjustments.length?data.adjustments.map(a=><section key={a.id} className="glass-panel p-4"><div className="flex justify-between gap-4"><div><h3>{a.motivo}</h3><p className="daily-hint">{accountName(a.conta_id)} · {formatDate(a.data)}</p></div><strong>{formatMoney(a.valor)}</strong></div><Button size="sm" variant="ghost" onClick={()=>open('adjustment.delete',{id:a.id})}>Excluir ajuste</Button></section>):<Empty title="Nenhum ajuste neste mês" text="Correções de saldo ficam registradas aqui."/>}</div>}
   </>}
   {mode==='cards'&&<>
    {!card?<Empty title="Seu primeiro cartão" text="Cadastre limite, fechamento e vencimento. Não pedimos número completo nem CVV."/>:<>
     <Label htmlFor="daily-card">Cartão</Label><select id="daily-card" className={nativeSelect+' mb-4 mt-2'} value={card.id} onChange={e=>setSelectedCard(e.target.value)}>{data.cards.map(c=><option key={c.id} value={c.id}>{c.nome}{c.arquivado?' (arquivado)':''}</option>)}</select>
     <BankCard card={{id:card.id,name:card.nome,network:card.bandeira,limit:card.limite,used:card.utilizado,closing:card.dia_fechamento,due:card.dia_vencimento,color:card.nome.toLowerCase().includes('nubank')?'#73279e':'#645023'}}/>
     <div className="daily-totals glass-panel p-4 mt-4"><div><span>Limite comprometido</span><strong>{formatMoney(card.utilizado)}</strong></div><div><span>{card.limite-card.utilizado<0?'Limite excedido':'Limite disponível'}</span><strong className="text-primary">{formatMoney(Math.abs(card.limite-card.utilizado))}</strong></div></div><p className="daily-hint">Inclui todas as parcelas futuras. Fechamento dia {card.dia_fechamento} · vencimento dia {card.dia_vencimento}.</p>
     <div className="flex flex-wrap gap-3 my-4"><Button variant="outline" onClick={()=>open('card.save',{id:card.id,nome:card.nome,limite:String(card.limite),dia_fechamento:card.dia_fechamento,dia_vencimento:card.dia_vencimento,bandeira:card.bandeira,arquivado:card.arquivado})}>Editar cartão</Button>{!card.arquivado&&<Button onClick={()=>open('purchase.save',{cartao_id:card.id})}><Plus/>Registrar compra</Button>}</div>
     <h2 className="font-semibold my-4">Fatura · {month.split('-').reverse().join('/')}</h2>
     {data.invoices.filter(f=>f.cartao_id===card.id).length?data.invoices.filter(f=>f.cartao_id===card.id).map(f=><section key={f.id} className="glass-panel p-5 space-y-3"><div className="daily-totals"><div><span>Total da fatura</span><strong>{formatMoney(f.total)}</strong></div><div><span>Saldo pendente</span><strong className="text-primary">{formatMoney(f.pendente)}</strong></div></div><p className="daily-hint">Pago: {formatMoney(f.pago)} · Fecha em {formatDate(f.fechamento)} · Vence em {formatDate(f.vencimento)}</p>{f.pendente>0?<Button onClick={()=>open('payment.save',{fatura_id:f.id,valor:String(f.pendente)})}>Registrar pagamento</Button>:<p className="money-positive text-sm">{f.total>0?'Fatura quitada':'Sem compras nesta fatura'}</p>}<Link className="subtle-link" href="/lancamentos">Consultar e editar compras<ArrowRight/></Link></section>):<Empty title="Sem fatura neste mês" text="As compras serão distribuídas conforme as datas de fechamento e vencimento."/>}
    </>}
    <h2 className="font-semibold mt-6 mb-3">Pagamentos registrados no mês</h2><p className="daily-hint">Histórico de todos os cartões. Excluir um registro reabre o saldo da fatura no app.</p>
    <div className="content-stack">{data.payments.length?data.payments.map(p=><section className="glass-panel p-4" key={p.id}><div className="flex justify-between gap-4"><div><h3>{accountName(p.conta_id)}</h3><p className="daily-hint">{formatDate(p.data)}</p></div><strong>{formatMoney(p.valor)}</strong></div><Button variant="ghost" size="sm" onClick={()=>open('payment.delete',{id:p.id})}>Excluir registro</Button></section>):<p className="daily-hint">Nenhum pagamento registrado neste mês.</p>}</div>
   </>}
   {maxCount>100&&<div className="daily-pagination"><Button variant="outline" disabled={page===0} onClick={()=>setPage(p=>p-1)}>Anterior</Button><span>Página {page+1} de {Math.ceil(maxCount/100)}</span><Button variant="outline" disabled={(page+1)*100>=maxCount} onClick={()=>setPage(p=>p+1)}>Próxima</Button></div>}
  </>}
  <Dialog open={chooser} onOpenChange={setChooser}><DialogContent><DialogHeader><DialogTitle>Novo registro</DialogTitle><DialogDescription>Escolha como esse movimento acontece.</DialogDescription></DialogHeader><div className="grid gap-3"><Button onClick={()=>open('transaction.save',{tipo:'despesa'})}>Despesa da conta</Button><Button variant="outline" onClick={()=>open('transaction.save',{tipo:'receita'})}>Receita</Button><Button variant="outline" onClick={()=>open('purchase.save')}>Compra no cartão</Button><Button variant="outline" onClick={()=>open('transfer.save')}>Transferência entre contas</Button></div></DialogContent></Dialog>
  <Dialog open={!!operation} onOpenChange={v=>{if(!v)close();}}><DialogContent onEscapeKeyDown={e=>{if(saving)e.preventDefault();}} onPointerDownOutside={e=>{if(saving)e.preventDefault();}}><DialogHeader><DialogTitle>{operation?operationTitles[operation]:''}</DialogTitle><DialogDescription>{operation?.endsWith('.delete')?'Confirme a exclusão deste registro do controle. Os saldos serão recalculados; nenhuma operação será enviada ao banco.':operation?notes[operation]:''}</DialogDescription></DialogHeader>
   {operation&&data&&<form onSubmit={save} className="space-y-4"><fieldset disabled={saving} className="space-y-4">{formFields(operation,values,data).map(f=>{const fieldId='daily-field-'+f.key;return f.kind==='checkbox'?<label className="flex gap-3 items-center text-sm" key={f.key}><input type="checkbox" checked={!!values[f.key]} onChange={e=>setValues(v=>({...v,[f.key]:e.target.checked}))}/>{f.label}</label>:<div key={f.key} className="space-y-2"><Label htmlFor={fieldId}>{f.label}</Label>{f.options?<select id={fieldId} className={nativeSelect} required value={String(values[f.key]??'')} onChange={e=>setValues(v=>({...v,[f.key]:e.target.value,...(f.key==='tipo'?{categoria_id:''}:{}),...(f.key==='status'?{data_realizacao:e.target.value==='realizado'?todayBR():null}:{})}))}><option value="">Selecione</option>{f.options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select>:f.kind==='textarea'?<textarea id={fieldId} className={nativeSelect} maxLength={f.max} value={String(values[f.key]??'')} onChange={e=>setValues(v=>({...v,[f.key]:e.target.value}))}/>:<Input id={fieldId} type={f.kind==='date'?'date':f.kind==='number'?'number':'text'} inputMode={f.kind==='money'?'decimal':undefined} required={!f.optional} min={f.kind==='number'?f.min:f.kind==='date'?'1900-01-01':undefined} max={f.kind==='number'?f.max:f.kind==='date'?(f.key==='data_competencia'||f.key==='data_vencimento'?'2200-12-31':todayBR()):undefined} maxLength={f.kind==='money'?16:f.max} value={String(values[f.key]??'')} onChange={e=>setValues(v=>({...v,[f.key]:f.kind==='number'?Number(e.target.value):e.target.value}))}/>}</div>;})}</fieldset>{error&&<PlanLink error={error}/>} {error&&<p role="alert" className="text-red-300 text-sm">{error}</p>}<div className="flex gap-3 flex-wrap"><Button type="submit" disabled={saving}>{saving?'Salvando…':operation.endsWith('.delete')?'Confirmar exclusão':'Salvar'}</Button><Button type="button" variant="outline" disabled={saving} onClick={close}>Cancelar</Button>{values.id&&formDelete[operation]&&<Button type="button" variant="ghost" className="text-red-300" disabled={saving} onClick={()=>open(formDelete[operation]!,{id:values.id})}>Excluir{operation==='purchase.save'?' compra inteira':''}</Button>}</div></form>}
  </DialogContent></Dialog><BottomNav/>
 </main>;
}
function Empty({title,text}:{title:string;text:string}){return <section className="glass-panel p-7 text-center"><Wallet className="size-8 text-primary mx-auto mb-3"/><h2 className="font-semibold">{title}</h2><p className="daily-hint mt-2">{text}</p></section>;}
function Transfers({rows,accountName,edit}:{rows:DailySnapshot['transfers'];accountName:(id:string)=>string;edit:(v:FormValues)=>void}){return rows.length?<div className="glass-panel transaction-list">{rows.map(t=><button className="transaction-row" key={t.id} onClick={()=>edit({id:t.id,conta_origem_id:t.conta_origem_id,conta_destino_id:t.conta_destino_id,valor:String(t.valor),data:t.data})}><span className="icon-tile icon-tile--neutral"><ArrowRightLeft/></span><span className="transaction-row__description"><strong>{accountName(t.conta_origem_id)} → {accountName(t.conta_destino_id)}</strong><small>{formatDate(t.data)}</small></span><span className="text-xs whitespace-nowrap">{formatMoney(t.valor)}</span></button>)}</div>:<Empty title="Nenhuma transferência neste mês" text="Movimentações entre suas contas aparecerão aqui."/>;}
