'use client';
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {Crown,Download,Check,Wallet,CreditCard,Target} from 'lucide-react';
import {useSubscription} from '@/hooks/useSubscription';
import {apiRequest,useResource} from '@/hooks/useResource';
import {ScreenHeader} from './finance-ui';
import {BottomNav} from '@/components/custom/bottom-nav';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Label} from '@/components/ui/label';
import {ResourceState,formatMoney} from '@/components/data/resource-state';
import {planSchemas,exportKinds} from '@/lib/domain/plans';
import type {Category} from '@/lib/database.types';
import {BillingPanel} from './billing-panel';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
type Choice={accounts:string[];cards:string[];goals:string[]};
const resourceNames={accounts:'Contas',cards:'Cartões',goals:'Metas'};
const exportLabels:Record<string,string>={contas:'Contas',categorias:'Categorias',transacoes:'Lançamentos',cartoes:'Cartões',faturas:'Faturas',transferencias:'Transferências',pagamentos_fatura:'Pagamentos de fatura',recorrencias:'Recorrências',versoes_recorrencia:'Versões de recorrência',orcamentos:'Orçamentos',metas:'Metas',aportes_metas:'Aportes e retiradas',ajustes_conta:'Ajustes de saldo'};
export default function PlanWorkspace(){
 const r=useSubscription(),p=r.data;const cats=useResource<{categories:Category[]}>('/api/categories?all=true');
 const [choice,setChoice]=useState<Choice>({accounts:[],cards:[],goals:[]}),[days,setDays]=useState(7),[threshold,setThreshold]=useState(80);
 const [category,setCategory]=useState({id:'',nome:'',tipo:'despesa',arquivada:false}),[kind,setKind]=useState('transacoes');
 const [saving,setSaving]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');const busy=useRef(false);
 useEffect(()=>{if(p){setChoice({accounts:p.accounts.filter(x=>x.allowed).map(x=>x.id),cards:p.cards.filter(x=>x.allowed).map(x=>x.id),goals:p.goals.filter(x=>x.allowed).map(x=>x.id)});setDays(p.alerts.antecedencia);setThreshold(p.alerts.limiar);}},[p]);
 async function save(operation:keyof typeof planSchemas,data:unknown){
  if(busy.current)return;setError('');setMessage('');const parsed=planSchemas[operation].safeParse(data);if(!parsed.success){setError(parsed.error.issues[0].message);return;}
  busy.current=true;setSaving(true);try{await apiRequest('/api/subscription',{method:'POST',body:JSON.stringify({operation,data:parsed.data})});setMessage('Preferências salvas.');if(operation==='category.save'){setCategory({id:'',nome:'',tipo:'despesa',arquivada:false});cats.reload();}r.reload();}catch(e){setError(e instanceof Error?e.message:'Não foi possível salvar.');}finally{busy.current=false;setSaving(false);}
 }
 const needsSelection=p&&!p.hasPlus&&(['accounts','cards','goals'] as const).some(k=>p[k].length>(p.limits[k]??Infinity));
 return <main className="app-shell finance-shell"><ScreenHeader title="Plano e assinatura"/><ResourceState {...r} retry={r.reload}/>{message&&<p role="status" className="daily-message">{message}</p>}{error&&<p role="alert" className="glass-panel p-4 mb-4 money-negative">{error}</p>}
 {p&&<div className="content-stack plan-workspace">
  <section className="balance-card plan-hero space-y-3"><div className="plan-hero-icon"><Crown aria-hidden="true"/></div><span className="plan-eyebrow">SEU PLANO</span><h2 className="text-2xl font-semibold">BOLSU {p.hasPlus?'Premium':p.limits.name}</h2><p className="text-sm text-muted-foreground">{p.hasPlus?'Mais possibilidades para cuidar do seu dinheiro.':'Seu controle diário continua no Gratuito.'}</p>{p.hasPlus&&<p className="text-sm">{p.subscription.ciclo==='yearly'?'Anual':p.subscription.ciclo==='monthly'?'Mensal':'Período de acesso'} · {p.subscription.status==='trialing'?'Teste até':'Acesso até'} {new Date((p.subscription.status==='trialing'?p.subscription.trial_ends_at:(p.subscription.stripe_access_until??p.subscription.current_period_end))!).toLocaleDateString('pt-BR')}{p.subscription.cancel_at_period_end||p.subscription.status==='canceled'?' · Renovação cancelada':''}</p>}</section><Tabs defaultValue="subscription"><TabsList className="plan-tabs" aria-label="Opções do plano"><TabsTrigger value="subscription">Assinatura</TabsTrigger><TabsTrigger value="preferences">Preferências</TabsTrigger><TabsTrigger value="data">Meus dados</TabsTrigger></TabsList><TabsContent value="subscription" className="content-stack"><BillingPanel onUpdate={r.reload}/>
  <details className="glass-panel p-5 plan-disclosure"><summary>Compare os benefícios</summary><div className="space-y-3">{[
   ['Contas ativas',String(p.matrix.free.accounts),'Sem limite comercial'],['Cartões ativos',String(p.matrix.free.cards),'Sem limite comercial'],['Metas ativas',String(p.matrix.free.goals),'Sem limite comercial'],
   ['Lançamentos, transferências e histórico','Ilimitados','Ilimitados'],['Parcelas e recorrência mensal','Incluídas','Incluídas'],['Orçamentos','Categorias padrão','Padrão e personalizadas'],['Exportação CSV','Incluída','Incluída'],['Visão do dinheiro','Saldo, compromissos e resumo','Também projeção e comparativos'],['Metas','Aportes e retiradas','Também estimativa mensal'],['Avisos internos','7 dias · orçamento em 80%/100%','Antecedência e limiar configuráveis'],
  ].map(([label,free,plus])=><div key={label} className="border-b pb-3 text-sm"><h3 className="font-semibold mb-1">{label}</h3><div className="grid grid-cols-2 gap-3"><p className="text-muted-foreground">Gratuito: {free}</p><p><span className="text-primary">Plus:</span> {plus}</p></div></div>)}</div><p className="daily-hint">Plus mensal e anual têm os mesmos recursos. Recursos futuros, como conexão bancária e notificações externas, não fazem parte desta oferta.</p></details>
  <section className="glass-panel p-5 space-y-4"><h2 className="font-semibold">Seus recursos</h2><div className="plan-resource-grid">{(['accounts','cards','goals'] as const).map(k=>{const Icon={accounts:Wallet,cards:CreditCard,goals:Target}[k];return <Link className="plan-resource" href={{accounts:'/contas',cards:'/cartoes',goals:'/metas'}[k]} key={k}><Icon aria-hidden="true"/><strong>{p[k].filter(x=>x.allowed).length}<small>{p.limits[k]!==null?' / '+p.limits[k]:' em uso'}</small></strong><span>{resourceNames[k]}</span></Link>;})}</div>
   {needsSelection&&<form onSubmit={e=>{e.preventDefault();save('selection',choice);}} className="space-y-4"><h3 className="font-semibold text-primary">Escolha o que continuará usando</h3><p className="daily-hint">Sem seleção, os grupos acima da franquia ficam sem novas operações. Recursos fora da seleção continuam consultáveis e exportáveis; faturas e previsões existentes podem ser quitadas, reservas retiradas e saldos transferidos. A geração de recorrências incompatíveis fica suspensa.</p>{(['accounts','cards','goals'] as const).map(k=><fieldset key={k} disabled={saving} className="space-y-2"><legend className="font-semibold text-sm mb-2">{resourceNames[k]} · escolha até {p.matrix.free[k]}</legend>{p[k].map(x=><label key={x.id} className="flex items-center gap-3 text-sm py-1"><input type="checkbox" checked={choice[k].includes(x.id)} onChange={e=>setChoice(v=>({...v,[k]:e.target.checked?[...v[k],x.id]:v[k].filter(id=>id!==x.id)}))}/>{x.name}</label>)}</fieldset>)}<Button disabled={saving} type="submit"><Check/>Salvar seleção</Button></form>}
   {p.pausedRecurrences>0&&<p className="home-warning">{p.pausedRecurrences} recorrência(s) suspensa(s) pelo plano. Parcelas e previsões já geradas continuam no histórico. Ao recuperar acesso, a geração volta a ficar disponível.</p>}
  </section>
  </TabsContent><TabsContent value="preferences" className="content-stack"><section className="glass-panel p-5 space-y-4"><h2 className="font-semibold">Categorias personalizadas {p.hasPlus?'':'· Plus'}</h2><p className="daily-hint">Organize receitas e despesas do seu jeito. Categorias padrão estão disponíveis em todos os planos.</p><ResourceState {...cats} retry={cats.reload}/>{cats.data?.categories.filter(c=>!c.padrao).map(c=><div key={c.id} className="flex flex-wrap justify-between gap-2 items-center text-sm"><span>{c.nome} · {c.tipo}{c.arquivada?' · Arquivada':''}</span>{p.hasPlus&&<Button variant="ghost" size="sm" onClick={()=>setCategory({id:c.id,nome:c.nome,tipo:c.tipo,arquivada:c.arquivada})}>Editar</Button>}</div>)}
   {p.hasPlus&&<form onSubmit={e=>{e.preventDefault();save('category.save',{...category,id:category.id||undefined});}} className="space-y-3"><fieldset disabled={saving} className="space-y-3"><Label htmlFor="category-name">Nome da categoria</Label><Input id="category-name" required maxLength={60} value={category.nome} onChange={e=>setCategory(v=>({...v,nome:e.target.value}))}/><Label htmlFor="category-type">Tipo</Label><select id="category-type" disabled={!!category.id} className="w-full rounded-xl border bg-glass-deep p-3" value={category.tipo} onChange={e=>setCategory(v=>({...v,tipo:e.target.value}))}><option value="despesa">Despesa</option><option value="receita">Receita</option></select>{category.id&&<label className="flex gap-3"><input type="checkbox" checked={category.arquivada} onChange={e=>setCategory(v=>({...v,arquivada:e.target.checked}))}/>Arquivada</label>}<div className="flex flex-wrap gap-3"><Button type="submit">{category.id?'Salvar categoria':'Criar categoria'}</Button>{category.id&&<Button type="button" variant="ghost" onClick={()=>setCategory({id:'',nome:'',tipo:'despesa',arquivada:false})}>Cancelar edição</Button>}</div></fieldset></form>}
  </section>
  <section className="glass-panel p-5 space-y-3"><h2 className="font-semibold">Avisos internos {p.hasPlus?'':'· regras padrão'}</h2><p className="daily-hint">Vencidos e próximos {p.alerts.antecedencia} dias; orçamento em {p.alerts.limiar}% e 100%. Não envia e-mail, push nem WhatsApp.</p>{p.hasPlus&&<form onSubmit={e=>{e.preventDefault();save('alerts',{antecedencia:days,limiar:threshold});}}><fieldset disabled={saving} className="space-y-3"><Label htmlFor="alert-days">Antecedência em dias (1–30)</Label><Input id="alert-days" type="number" min={1} max={30} value={days} onChange={e=>setDays(Number(e.target.value))}/><Label htmlFor="alert-threshold">Avisar ao utilizar (%)</Label><Input id="alert-threshold" type="number" min={50} max={100} value={threshold} onChange={e=>setThreshold(Number(e.target.value))}/><Button type="submit">Salvar avisos</Button></fieldset></form>}<Link href="/notificacoes" className="subtle-link">Ver avisos</Link></section>
  </TabsContent><TabsContent value="data" className="content-stack">{p.hasPlus&&<Comparisons/>}
  <section className="glass-panel p-5 space-y-3"><h2 className="font-semibold">Exporte seu histórico</h2><p className="daily-hint">Escolha os dados e baixe uma cópia em CSV. Disponível em todos os planos.</p><Label htmlFor="export-kind">Dados para exportar</Label><select id="export-kind" className="w-full rounded-xl border bg-glass-deep p-3" value={kind} onChange={e=>setKind(e.target.value)}>{exportKinds.map(k=><option key={k} value={k}>{exportLabels[k]}</option>)}</select><Button asChild variant="outline"><a href={'/api/export?kind='+kind} download><Download/>Baixar CSV</a></Button></section>
 </TabsContent></Tabs></div>}<BottomNav/></main>;
}
function Comparisons(){const [period,setPeriod]=useState(3);const r=useResource<{months:{mes:string;receitas:number;despesas:number}[]}>('/api/comparisons');return <section className="glass-panel p-5"><h2 className="font-semibold">Seu dinheiro mês a mês</h2><div className="flex gap-2 my-4" role="group" aria-label="Período do comparativo">{[3,6,12].map(n=><Button key={n} size="sm" variant={period===n?'default':'outline'} aria-pressed={period===n} onClick={()=>setPeriod(n)}>{n} meses</Button>)}</div><p className="daily-hint">Por competência: receitas realizadas e despesas realizadas + parcelas de cartão. Todas as contas; pagamentos de fatura não duplicam despesa. O mês atual ainda está em andamento.</p><ResourceState {...r} retry={r.reload}/>{r.data&&<div className="space-y-3">{r.data.months.slice(-period).map(m=><div key={m.mes} className="text-sm border-b pb-3"><h3 className="font-semibold">{m.mes.slice(0,7).split('-').reverse().join('/')}</h3><div className="flex justify-between flex-wrap gap-2"><span className="money-positive">Receitas {formatMoney(m.receitas)}</span><span>Despesas {formatMoney(m.despesas)}</span></div></div>)}</div>}</section>;}
