import {PGlite} from '@electric-sql/pglite';
import {readFileSync} from 'node:fs';
import {randomUUID} from 'node:crypto';
import {test,before,after,beforeEach} from 'node:test';
import assert from 'node:assert/strict';
let db,A,B,a,b,expense,income,card;
const migrations=['202609220001_foundation.sql','202609220002_daily_control.sql'].map(n=>readFileSync(new URL('../../supabase/migrations/'+n,import.meta.url),'utf8'));
async function who(id){await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);await db.exec('set role authenticated');}
async function op(operation,data,key=randomUUID()){return (await db.query('select public.bolsu_daily($1,$2::jsonb,$3) result',[operation,JSON.stringify(data),key])).rows[0].result;}
async function snapshot(month='2026-01-01',page=0){return (await db.query('select public.bolsu_daily_snapshot($1,$2) result',[month,page])).rows[0].result;}
const tx=(extra={})=>({descricao:'Despesa',tipo:'despesa',valor:'10.00',categoria_id:expense,conta_id:a,data_competencia:'2026-01-03',data_vencimento:'2026-01-03',data_realizacao:'2026-01-03',status:'realizado',...extra});
const buy=(extra={})=>({cartao_id:card,descricao:'Compra',valor:'100.00',categoria_id:expense,data_compra:'2026-01-02',parcelas:3,...extra});
before(async()=>{db=new PGlite();await db.exec(`create role anon nologin;create role authenticated nologin;create schema auth;create table auth.users(id uuid primary key,raw_user_meta_data jsonb default '{}');create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema public,auth to authenticated,anon;grant execute on function auth.uid() to authenticated,anon;`);for(const sql of migrations)await db.exec(sql);});
after(async()=>db?.close());
beforeEach(async()=>{A=randomUUID();B=randomUUID();await db.exec('reset role');await db.query('insert into auth.users(id) values($1),($2)',[A,B]);await who(A);a=(await op('account.save',{nome:'A',tipo:'corrente',saldo_inicial:'1000',data_saldo_inicial:'2020-01-01',incluir_no_disponivel:true})).id;b=(await op('account.save',{nome:'B',tipo:'carteira',saldo_inicial:'0',data_saldo_inicial:'2020-01-01',incluir_no_disponivel:true})).id;const cats=(await snapshot()).categories;expense=cats.find(x=>x.tipo==='despesa').id;income=cats.find(x=>x.tipo==='receita').id;card=(await op('card.save',{nome:'Teste',limite:'5000',dia_fechamento:10,dia_vencimento:20,bandeira:'Visa'})).id;});
test('realização, edição, previsão e exclusão recalculam saldo sem apagar trilha',async()=>{const t=await op('transaction.save',tx());assert.equal((await snapshot()).accounts.find(x=>x.id===a).saldo_atual,990);await op('transaction.save',tx({id:t.id,valor:'20'}));assert.equal((await snapshot()).accounts.find(x=>x.id===a).saldo_atual,980);await op('transaction.save',tx({id:t.id,status:'previsto',data_realizacao:null}));assert.equal((await snapshot()).accounts.find(x=>x.id===a).saldo_atual,1000);await op('transaction.delete',{id:t.id});assert.equal((await snapshot()).counts.transactions,0);assert.equal((await db.query('select excluida from transacoes where id=$1',[t.id])).rows[0].excluida,true);});
test('transferência não vira receita ou despesa e reversão restaura ambas as contas',async()=>{const t=await op('transfer.save',{conta_origem_id:a,conta_destino_id:b,valor:'125.45',data:'2026-01-02'});let s=await snapshot();assert.equal(s.accounts.find(x=>x.id===a).saldo_atual,874.55);assert.equal(s.accounts.find(x=>x.id===b).saldo_atual,125.45);assert.deepEqual(s.totals,{income:0,expenses:0});await op('transfer.save',{id:t.id,conta_origem_id:b,conta_destino_id:a,valor:'10',data:'2026-01-03'});s=await snapshot();assert.equal(s.accounts.find(x=>x.id===a).saldo_atual,1010);await op('transfer.delete',{id:t.id});assert.equal((await snapshot()).accounts.find(x=>x.id===a).saldo_atual,1000);});
test('100 reais em 3 parcelas somam exatamente 100 e comprometem todo o limite',async()=>{await op('purchase.save',buy());const rows=(await db.query('select valor from transacoes where usuario_id=$1 order by parcela',[A])).rows.map(x=>Number(x.valor));assert.deepEqual(rows,[33.34,33.33,33.33]);const s=await snapshot();assert.equal(s.cards[0].utilizado,100);assert.equal(s.accounts.find(x=>x.id===a).saldo_atual,1000);assert.equal(s.totals.expenses,33.34);});
test('pagamento parcial movimenta caixa uma vez e libera somente o valor pago',async()=>{await op('purchase.save',buy({parcelas:1}));const f=(await snapshot()).invoices[0];const p=await op('payment.save',{conta_id:a,fatura_id:f.id,valor:'40',data:'2026-01-20'});let s=await snapshot();assert.equal(s.invoices[0].pendente,60);assert.equal(s.cards[0].utilizado,60);assert.equal(s.accounts.find(x=>x.id===a).saldo_atual,960);assert.equal(s.totals.expenses,100);await assert.rejects(op('payment.save',{conta_id:a,fatura_id:f.id,valor:'61',data:'2026-01-20'}),/excede/);await op('payment.delete',{id:p.id});s=await snapshot();assert.equal(s.invoices[0].pendente,100);assert.equal(s.accounts.find(x=>x.id===a).saldo_atual,1000);});
test('mesma chave não duplica gravação e payload alterado é recusado',async()=>{const key=randomUUID(),payload=tx();const first=await op('transaction.save',payload,key);assert.deepEqual(await op('transaction.save',payload,key),first);assert.equal((await snapshot()).counts.transactions,1);await assert.rejects(op('transaction.save',tx({valor:'9'}),key),/outros dados/);});
test('compra inteira só pode ser alterada quando as faturas não têm pagamentos',async()=>{const p=await op('purchase.save',buy());await op('purchase.save',buy({id:p.id,valor:'90'}));assert.equal((await snapshot()).cards[0].utilizado,90);const f=(await snapshot()).invoices[0];const pay=await op('payment.save',{conta_id:a,fatura_id:f.id,valor:'10',data:'2026-01-20'});await assert.rejects(op('purchase.delete',{id:p.id}),/pagamento/);assert.equal((await snapshot()).cards[0].utilizado,80);await op('payment.delete',{id:pay.id});await op('purchase.delete',{id:p.id});assert.equal((await snapshot()).cards[0].utilizado,0);});
test('fechamento no dia da compra vai ao próximo ciclo e dia 31 respeita fevereiro e ano bissexto',async()=>{const c=await op('card.save',{nome:'31',limite:'5000',dia_fechamento:31,dia_vencimento:5,bandeira:'Elo'});await op('purchase.save',buy({cartao_id:c.id,data_compra:'2024-01-31',parcelas:3}));const fs=(await db.query('select fechamento::text,vencimento::text from faturas where cartao_id=$1 order by competencia',[c.id])).rows;assert.deepEqual(fs.map(f=>[f.fechamento,f.vencimento]),[['2024-02-29','2024-03-05'],['2024-03-31','2024-04-05'],['2024-04-30','2024-05-05']]);});
test('categorias incompatíveis, datas futuras realizadas e precisão excessiva são recusadas',async()=>{await assert.rejects(op('transaction.save',tx({categoria_id:income})),/Categoria/);await assert.rejects(op('transaction.save',tx({valor:'1.001'})),/monetário/);await assert.rejects(op('transaction.save',tx({data_realizacao:'2199-01-01'})),/realização/);await assert.rejects(op('transaction.save',tx({data_vencimento:'2019-01-01',data_realizacao:null,status:'previsto'})),/abertura/);await assert.rejects(op('purchase.save',buy({valor:'0.01',parcelas:2})),/parcelas/);await assert.rejects(op('transfer.save',{conta_origem_id:a,conta_destino_id:a,valor:'10',data:'2026-01-01'}),/diferentes/);});
test('outra identidade não vê nem altera compras, pagamentos, contas ou lançamentos',async()=>{const t=await op('transaction.save',tx()),p=await op('purchase.save',buy());const f=(await snapshot()).invoices[0];await who(B);const other=(await op('account.save',{nome:'Outra',tipo:'corrente',saldo_inicial:'0',data_saldo_inicial:'2020-01-01',incluir_no_disponivel:true})).id;const s=await snapshot();assert.equal(s.transactions.length,0);assert.equal(s.cards.length,0);assert.equal(s.invoices.length,0);await assert.rejects(op('transaction.delete',{id:t.id}),/não encontrado/);await assert.rejects(op('purchase.delete',{id:p.id}),/não encontrada/);await assert.rejects(op('payment.save',{conta_id:other,fatura_id:f.id,valor:'1',data:'2026-01-01'}),/não encontrada/);await assert.rejects(op('transaction.save',tx()),/conta ativa/);await assert.rejects(op('account.save',{id:a,nome:'Invasão',tipo:'corrente',incluir_no_disponivel:true}),/não encontrada/);});
test('ajuste identificado não vira receita e arquivamento preserva saldo e histórico',async()=>{const adj=await op('adjustment.save',{conta_id:b,valor:'25',data:'2026-01-01',motivo:'Correção de abertura'});assert.equal((await snapshot()).accounts.find(x=>x.id===b).saldo_atual,25);assert.equal((await snapshot()).totals.income,0);await assert.rejects(op('account.save',{id:b,nome:'B',tipo:'carteira',incluir_no_disponivel:true,arquivada:true}),/Zere/);await op('adjustment.delete',{id:adj.id});await op('account.save',{id:b,nome:'B',tipo:'carteira',incluir_no_disponivel:true,arquivada:true});await assert.rejects(op('adjustment.save',{conta_id:b,valor:'5',data:'2026-01-01',motivo:'Erro'}),/ativa/);});
test('previsões futuras aparecem no mês correto e totais não truncam com paginação',async()=>{for(let i=0;i<101;i++)await op('transaction.save',tx({data_competencia:'2199-01-01',data_vencimento:'2199-01-01',data_realizacao:null,status:'previsto',valor:'1'}));const s=await snapshot('2199-01-01');assert.equal(s.transactions.length,100);assert.equal(s.counts.transactions,101);assert.equal(s.totals.expenses,101);assert.equal((await snapshot('2199-01-01',1)).transactions.length,1);assert.equal(s.accounts.find(x=>x.id===a).saldo_atual,1000);});
test('anônimo e escrita direta continuam bloqueados; campos de proprietário não são aceitos',async()=>{await assert.rejects(op('transaction.save',tx({usuario_id:B})),/campos inválidos/);await assert.rejects(db.query('update transacoes set valor=1'),/permission denied/);await assert.rejects(db.query('select * from operacoes_diarias'),/permission denied/);await db.exec('reset role;set role anon');await assert.rejects(op('transaction.save',tx()),/permission denied/);await assert.rejects(snapshot(),/permission denied/);});
test('filtros do servidor procuram também registros além da primeira página',async()=>{for(let i=0;i<101;i++)await op('transaction.save',tx({descricao:i===0?'Única antiga':'Comum',valor:'1'}));const r=(await db.query("select bolsu_daily_snapshot('2026-01-01',0,'Única','all','all',null) result")).rows[0].result;assert.equal(r.transactions.length,1);assert.equal(r.counts.transactions,1);assert.equal(r.totals.expenses,1);});
test('falha ao editar compra reverte a exclusão das parcelas antigas',async()=>{const p=await op('purchase.save',buy());await assert.rejects(op('purchase.save',buy({id:p.id,categoria_id:income})),/categoria/);assert.equal((await snapshot()).cards[0].utilizado,100);assert.equal((await db.query('select count(*)::int n from transacoes where compra_id=$1 and not excluida',[p.id])).rows[0].n,3);});
test('quitação integral aparece no filtro realizado sem transformar pagamento em despesa',async()=>{await op('purchase.save',buy({parcelas:1}));const f=(await snapshot()).invoices[0];await op('payment.save',{conta_id:a,fatura_id:f.id,valor:'100',data:'2026-01-20'});const s=(await db.query("select bolsu_daily_snapshot('2026-01-01',0,'','all','realizado',null) result")).rows[0].result;assert.equal(s.transactions.length,1);assert.equal(s.totals.expenses,100);assert.equal(s.cards[0].utilizado,0);});
