'use client';
import { useState } from 'react';
import Link from 'next/link';
import { BatteryFull, ChevronRight, Filter, Plus, Signal, Wifi } from 'lucide-react';
import { Brand, BrandSplash } from '@/components/brand/brand';
import { NavigationBar } from '@/components/custom/bottom-nav';
import { BalanceCard, BankCard, CardSummary, CategoryBreakdown, FilterPills, FloatingAdd, GoalCards, HeaderIdentity, RoundButton, ScreenHeader, TransactionRows } from '@/components/finance/finance-ui';
import { MoreMenu } from '@/components/finance/more-menu';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { formatMoney } from '@/components/data/resource-state';
const categories=[{name:'Alimentação',amount:1200,color:'#ff673e'},{name:'Transporte',amount:450,color:'#ffcb16'},{name:'Moradia',amount:1800,color:'#596371'},{name:'Lazer',amount:300,color:'#7e8998'},{name:'Outros',amount:250,color:'#3d424c'}];
const transactions=[{id:'1',name:'Aluguel',date:'04/09/2026',amount:1800,income:false,icon:'house'},{id:'2',name:'Cartão Nubank',date:'09/09/2026',amount:850,income:false,icon:'card'},{id:'3',name:'Internet',date:'14/09/2026',amount:120,income:false,icon:'wifi'},{id:'4',name:'Salário',date:'01/09/2026',amount:5000,income:true,icon:'income'},{id:'5',name:'Supermercado',date:'12/09/2026',amount:320,income:false,icon:'shopping'},{id:'6',name:'Combustível',date:'10/09/2026',amount:180,income:false,icon:'fuel'},{id:'7',name:'Restaurante',date:'08/09/2026',amount:95,income:false,icon:'food'}];
const goals=[{id:'1',title:'Viagem',current:3200,target:5000,icon:'plane'},{id:'2',title:'Entrada da casa',current:12000,target:30000,icon:'house'},{id:'3',title:'PC novo',current:2500,target:8000,icon:'laptop'},{id:'4',title:'PlayStation 5',current:1200,target:3500,icon:'game'}];
const cards=[{id:'1',name:'Nubank',network:'Mastercard',limit:5000,used:850,closing:10,due:9,color:'#73279e',lastDigits:'3456'},{id:'2',name:'Inter',network:'Visa',limit:3000,used:800,closing:10,due:20,color:'#bd5c18',lastDigits:'7890'}];
function Phone({id,label,children,splash=false}:{id:string;label:string;children:React.ReactNode;splash?:boolean}) {return <section id={id} aria-label={label} className="theme-phone"><div className="theme-phone__status" aria-hidden="true"><span>9:41</span><span><Signal/><Wifi/><BatteryFull/></span></div>{splash?children:<div className="theme-phone__body">{children}</div>}{splash&&<div className="home-indicator"/>}</section>;}
export default function ThemePage(){
const [visible,setVisible]=useState(true),[type,setType]=useState('all'),[goalFilter,setGoalFilter]=useState('all'),[card,setCard]=useState(0),[detail,setDetail]=useState('');
const filtered=transactions.filter(t=>type==='all'||(type==='income'?t.income:!t.income));
function navigate(path:string){const panel=document.getElementById(`theme-${path.slice(1)}`);if(panel)panel.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'center'});else setDetail('Esta é uma prévia visual. Acesse sua conta para utilizar as áreas do app.');}
const nav=(active:string)=><NavigationBar active={active} preview onNavigate={navigate}/>;
const add=()=>setDetail('Os formulários continuam disponíveis nas telas do app. Esta prévia mostra a nova identidade com dados de exemplo.');
return <main className="theme-page"><header className="theme-heading"><Brand/><div><h1>Uma nova fase para o seu dinheiro.</h1><p>Prévia do tema · dados de exemplo</p></div><Link href="/login" className="subtle-link">Entrar no app<ChevronRight/></Link></header><div className="theme-board">
<Phone id="theme-marca" label="Identidade BOLSUAPP" splash><BrandSplash/></Phone>
<Phone id="theme-dashboard" label="Início"><HeaderIdentity name="Usuário" onAlerts={()=>setDetail('Suas notificações ficam reunidas aqui.')} onProfile={()=>navigate('/mais')}/><BalanceCard balance={5420.50} income={8500} expenses={4000} visible={visible} onToggle={()=>setVisible(v=>!v)}/><CategoryBreakdown categories={categories} visible={visible} action={<RoundButton label="Ver lançamentos" onClick={()=>navigate('/lancamentos')}><ChevronRight/></RoundButton>}/><FloatingAdd preview onClick={add}/>{nav('/dashboard')}</Phone>
<Phone id="theme-lancamentos" label="Lançamentos"><ScreenHeader title="Lançamentos"/><div className="filter-toolbar"><FilterPills values={[{value:'all',label:'Todos'},{value:'income',label:'Receitas'},{value:'expense',label:'Despesas'}]} selected={type} onChange={setType}/><RoundButton label="Informações dos filtros" className="round-button--plain" onClick={()=>setDetail('Use as opções Todos, Receitas e Despesas para experimentar os filtros desta prévia.')}><Filter/></RoundButton></div><div className="month-heading"><span>Setembro 2026</span><strong>{formatMoney(filtered.reduce((sum,t)=>sum+(t.income?t.amount:-t.amount),0))}</strong></div><TransactionRows items={filtered} onSelect={item=>setDetail(`${item.name} · ${item.date} · ${formatMoney(item.amount)}. Lançamento de exemplo.`)}/><FloatingAdd preview onClick={add}/>{nav('/lancamentos')}</Phone>
<Phone id="theme-cartoes" label="Meus Cartões"><ScreenHeader title="Meus Cartões"><RoundButton label="Adicionar cartão" onClick={add}><Plus/></RoundButton></ScreenHeader><BankCard card={cards[card]}/><div className="carousel-dots">{cards.map((c,i)=><button key={c.id} aria-label={`Mostrar cartão ${c.name}`} aria-pressed={card===i} onClick={()=>setCard(i)}/>)}</div><CardSummary card={cards[card]}/>{nav('/cartoes')}</Phone>
<Phone id="theme-metas" label="Metas"><ScreenHeader title="Metas"><RoundButton label="Adicionar meta" onClick={add}><Plus/></RoundButton></ScreenHeader><div className="filter-toolbar"><FilterPills values={[{value:'all',label:'Todas'},{value:'active',label:'Em andamento'},{value:'done',label:'Concluídas'}]} selected={goalFilter} onChange={setGoalFilter}/></div><GoalCards goals={goalFilter==='done'?[]:goals} onSelect={goal=>setDetail(`${goal.title}: ${formatMoney(goal.current)} de ${formatMoney(goal.target)}. Meta de exemplo.`)}/>{nav('/metas')}</Phone>
<Phone id="theme-mais" label="Mais"><ScreenHeader title="Mais"/><MoreMenu name="Usuário" email="usuario@email.com" onNavigate={navigate}/>{nav('/mais')}</Phone>
</div><p className="theme-note">Organize. Planeje. Conquiste. · Valores ilustrativos, sem vínculo com sua conta.</p><Dialog open={!!detail} onOpenChange={open=>{if(!open)setDetail('');}}><DialogContent><DialogHeader><DialogTitle>Prévia BOLSUAPP</DialogTitle><DialogDescription>{detail}</DialogDescription></DialogHeader></DialogContent></Dialog></main>;
}
